import base64
import io

import segno


def get_printable_html(qr_code: segno.QRCode, ssid: str) -> str:
    """
    Generates a print-friendly HTML string for an A4 page with the QR code.

    Args:
        qr_code: The segno.QRCode object.
        ssid: The SSID of the network (for display).

    Returns:
        A string containing the HTML content.
    """
    # Convert QR code to base64 PNG
    buffer = io.BytesIO()
    qr_code.save(buffer, kind="png", scale=20, border=2)
    buffer.seek(0)
    img_str = base64.b64encode(buffer.getvalue()).decode("utf-8")
    
    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>WiFi QR Code - {ssid}</title>
        <style>
            @page {{
                size: A4;
                margin: 0;
            }}
            body {{
                font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
                margin: 0;
                padding: 0;
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: center;
                height: 100vh;
                text-align: center;
                background-color: white;
                color: #333;
            }}
            .container {{
                width: 80%;
                max-width: 800px;
                padding: 40px;
                border: 2px solid #eee;
                border-radius: 20px;
            }}
            h1 {{
                font-size: 3em;
                margin-bottom: 0.5em;
                font-weight: 700;
                word-break: break-all;
            }}
            .qr-code {{
                width: 10cm;
                height: 10cm;
                margin: 2em auto;
                display: block;
            }}
            .instructions {{
                font-size: 1.5em;
                color: #555;
                margin-top: 2em;
            }}
            .footer {{
                margin-top: 4em;
                font-size: 0.8em;
                color: #999;
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>{ssid}</h1>
            <img src="data:image/png;base64,{img_str}" alt="WiFi QR Code" class="qr-code">
            <div class="instructions">
                Scan to Connect
            </div>
            <div class="footer">
                Generated by WiFi QR Share
            </div>
        </div>
        <script>
            window.onload = function() {{
                window.print();
            }}
        </script>
    </body>
    </html>
    """
    return html_content
